name: Migrate Data to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1

jobs:
  migrate_data:
    name: Run Data Import Script
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Import Script on EC2 (via SSM)
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=bankedge-app-server" \
          --max-concurrency "1" \
          --comment "Running Data Migration" \
          --comment "Running Data Migration" \
          --parameters commands='[
            "docker exec bankedge python scripts/import_db.py"
          ]'
