name: Terraform Manager

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Resource Target'
        required: true
        default: 'Main Services'
        type: choice
        options:
        - Main Services
        - Backend (Bootstrap)
      command:
        description: 'Action'
        required: true
        default: 'deploy'
        type: choice
        options:
        - deploy
        - destroy

env:
  AWS_REGION: ap-southeast-1
  TF_VAR_db_username: "dbadmin"
  TF_VAR_db_password: ${{ secrets.TF_DB_PASSWORD }}
  TF_VAR_docker_image: ${{ secrets.DOCKER_USERNAME }}/bankedge:latest

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Determine Directory
      id: dir
      run: |
        if [ "${{ inputs.target }}" == "Backend (Bootstrap)" ]; then
          echo "path=./terraform/backend" >> $GITHUB_OUTPUT
        else
          echo "path=./terraform" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Init
      working-directory: ${{ steps.dir.outputs.path }}
      run: terraform init

    - name: Terraform Format Check
      working-directory: ${{ steps.dir.outputs.path }}
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      working-directory: ${{ steps.dir.outputs.path }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ steps.dir.outputs.path }}
      run: terraform plan -out=tfplan

    - name: Terraform Run
      working-directory: ${{ steps.dir.outputs.path }}
      run: |
        echo "Running ${{ inputs.command }} on ${{ inputs.target }}..."
        
        if [ "${{ inputs.command }}" == "deploy" ]; then
          terraform apply -input=false tfplan
        elif [ "${{ inputs.command }}" == "destroy" ]; then
          terraform destroy -auto-approve
        fi
